### ISSUE TITLE
PatternRecognition-FaceRecognition仓库

### ISSUE THREAD

**Issue by iambajie** [wangling1820/PatternRecognition-FaceRecognition#1]
感谢博主分享，关于classified_by_models代码里有一些问题想请教下：初始化时导入的模型vgg.h5和googlenet.h5是使用的别人预训练的模型吗，博主能否分享下？
相关代码：
def __init__(self, type):
        super().__init__(type)
        if self.type is 'GoogLeNet':
            self.model_path = './weights/GoogLeNet.h5'
            self.layer_name = 'Avg_Pooling'
        elif self.type is 'VGG':
            self.model_path = './weights/VGG.h5'
            self.layer_name = 'fc2'
        else:
            raise RuntimeError('输入的参数:type无效!')

**Comment by wangling1820** [comment]
> 感谢博主分享，关于classified_by_models代码里有一些问题想请教下：初始化时导入的模型vgg.h5和googlenet.h5是使用的别人预训练的模型吗，博主能否分享下？
> 相关代码：
> def **init**(self, type):
> super().**init**(type)
> if self.type is 'GoogLeNet':
> self.model_path = './weights/GoogLeNet.h5'
> self.layer_name = 'Avg_Pooling'
> elif self.type is 'VGG':
> self.model_path = './weights/VGG.h5'
> self.layer_name = 'fc2'
> else:
> raise RuntimeError('输入的参数:type无效!')

这是官方的预训练模型数据，文件过大无法放大仓库里，这里是百度云盘链接：https://pan.baidu.com/s/17YCOl0arh3et4RGSWv6JBw 
提取码：4t59

**Comment by iambajie** [comment]
> > 感谢博主分享，关于classified_by_models代码里有一些问题想请教下：初始化时导入的模型vgg.h5和googlenet.h5是使用的别人预训练的模型吗，博主能否分享下？
> > 相关代码：
> > def **init**(self, type):
> > super().**init**(type)
> > if self.type is 'GoogLeNet':
> > self.model_path = './weights/GoogLeNet.h5'
> > self.layer_name = 'Avg_Pooling'
> > elif self.type is 'VGG':
> > self.model_path = './weights/VGG.h5'
> > self.layer_name = 'fc2'
> > else:
> > raise RuntimeError('输入的参数:type无效!')
> 
> 这是官方的预训练模型数据，文件过大无法放大仓库里，这里是百度云盘链接：https://pan.baidu.com/s/17YCOl0arh3et4RGSWv6JBw
> 提取码：4t59

好的，感谢博主
